apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  namespace: sso-pilot
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  APP_NAME: "Analytics Dashboard"
  APP_REQUIRED_ROLE: app1-subscriber
  APP_HOST: app1.sso.local
  APP_CLIENT_ID: app1-client
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/sso-pilot
