apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: sso-pilot
data:
  KC_DB: postgres
  KC_HOSTNAME: keycloak.sso.local
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: edge
  KC_HEALTH_ENABLED: "true"
