apiVersion: v1
kind: ConfigMap
metadata:
  name: app5-config
  namespace: sso-pilot
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  APP_NAME: "Support Center"
  APP_REQUIRED_ROLE: app5-subscriber
  APP_HOST: app5.sso.local
  APP_CLIENT_ID: app5-client
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/sso-pilot
