server:
  port: 8080

app:
  name: ${APP_NAME:My App}
  required-role: ${APP_REQUIRED_ROLE:app1-subscriber}
  host: ${APP_HOST:app1.sso.local}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${APP_CLIENT_ID:app1-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: "http://${app.host}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/sso-pilot}
            user-name-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
