apiVersion: v1
kind: ConfigMap
metadata:
  name: app4-config
  namespace: sso-pilot
data:
  SPRING_PROFILES_ACTIVE: kubernetes
  APP_NAME: "Finance Tracker"
  APP_REQUIRED_ROLE: app4-subscriber
  APP_HOST: app4.sso.local
  APP_CLIENT_ID: app4-client
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/sso-pilot
